// This file is auto-generated by @hey-api/openapi-ts

export type ClientOptions = {
    baseUrl: `${string}://${string}` | (string & {});
};

/**
 * HTTPValidationError
 */
export type HttpValidationError = {
    /**
     * Detail
     */
    detail?: Array<ValidationError>;
};

/**
 * IalaLightCreate
 */
export type IalaLightCreate = {
    /**
     * Name
     */
    name: string;
    /**
     * Category
     */
    category: string;
    /**
     * Rhythm
     */
    rhythm: string;
    /**
     * Description
     */
    description?: string | null;
    /**
     * Config
     */
    config: {
        [key: string]: unknown;
    };
};

/**
 * IalaLightResponse
 */
export type IalaLightResponse = {
    /**
     * Name
     */
    name: string;
    /**
     * Category
     */
    category: string;
    /**
     * Rhythm
     */
    rhythm: string;
    /**
     * Description
     */
    description?: string | null;
    /**
     * Config
     */
    config: {
        [key: string]: unknown;
    };
    /**
     * Id
     */
    id: string;
    /**
     * Created At
     */
    created_at: string;
};

/**
 * LoginRequest
 */
export type LoginRequest = {
    /**
     * Username
     */
    username: string;
    /**
     * Password
     */
    password: string;
};

/**
 * QuizAttemptCreate
 */
export type QuizAttemptCreate = {
    /**
     * User Id
     */
    user_id: string;
    /**
     * Quiz Id
     */
    quiz_id: string;
    /**
     * Responses
     */
    responses?: Array<QuizResponseCreate>;
};

/**
 * QuizAttemptResponse
 */
export type QuizAttemptResponse = {
    /**
     * Id
     */
    id: string;
    /**
     * User Id
     */
    user_id: string;
    /**
     * Quiz Id
     */
    quiz_id: string;
    /**
     * Created At
     */
    created_at: string;
    /**
     * Responses
     */
    responses?: Array<QuizResponseItemSchema>;
};

/**
 * QuizCreate
 */
export type QuizCreate = {
    /**
     * Name
     */
    name?: string | null;
    /**
     * Questions
     */
    questions?: Array<QuizQuestionCreate>;
};

/**
 * QuizQuestionCreate
 */
export type QuizQuestionCreate = {
    /**
     * Question Text
     */
    question_text?: string | null;
    /**
     * Iala Light Id
     */
    iala_light_id?: string | null;
    /**
     * Position
     */
    position?: number;
    /**
     * Options
     */
    options?: Array<QuizQuestionOptionCreate>;
};

/**
 * QuizQuestionOptionCreate
 */
export type QuizQuestionOptionCreate = {
    /**
     * Option Text
     */
    option_text?: string | null;
    /**
     * Iala Light Id
     */
    iala_light_id?: string | null;
    /**
     * Is Correct
     */
    is_correct?: boolean;
    /**
     * Position
     */
    position?: number;
};

/**
 * QuizQuestionOptionResponse
 */
export type QuizQuestionOptionResponse = {
    /**
     * Option Text
     */
    option_text?: string | null;
    /**
     * Iala Light Id
     */
    iala_light_id?: string | null;
    /**
     * Is Correct
     */
    is_correct?: boolean;
    /**
     * Position
     */
    position?: number;
    /**
     * Id
     */
    id: string;
    /**
     * Question Id
     */
    question_id: string;
    /**
     * Created At
     */
    created_at: string;
};

/**
 * QuizQuestionOptionUpdate
 */
export type QuizQuestionOptionUpdate = {
    /**
     * Option Text
     */
    option_text?: string | null;
    /**
     * Iala Light Id
     */
    iala_light_id?: string | null;
    /**
     * Is Correct
     */
    is_correct?: boolean | null;
    /**
     * Position
     */
    position?: number | null;
};

/**
 * QuizQuestionResponse
 */
export type QuizQuestionResponse = {
    /**
     * Question Text
     */
    question_text?: string | null;
    /**
     * Iala Light Id
     */
    iala_light_id?: string | null;
    /**
     * Position
     */
    position?: number;
    /**
     * Id
     */
    id: string;
    /**
     * Quiz Id
     */
    quiz_id: string;
    /**
     * Created At
     */
    created_at: string;
    /**
     * Options
     */
    options?: Array<QuizQuestionOptionResponse>;
};

/**
 * QuizQuestionUpdate
 */
export type QuizQuestionUpdate = {
    /**
     * Question Text
     */
    question_text?: string | null;
    /**
     * Iala Light Id
     */
    iala_light_id?: string | null;
    /**
     * Position
     */
    position?: number | null;
};

/**
 * QuizResponse
 */
export type QuizResponse = {
    /**
     * Name
     */
    name?: string | null;
    /**
     * Id
     */
    id: string;
    /**
     * Created At
     */
    created_at: string;
    /**
     * Questions
     */
    questions?: Array<QuizQuestionResponse>;
};

/**
 * QuizResponseCreate
 */
export type QuizResponseCreate = {
    /**
     * Question Id
     */
    question_id: string;
    /**
     * Selected Option Id
     */
    selected_option_id: string;
};

/**
 * QuizResponseItemSchema
 */
export type QuizResponseItemSchema = {
    /**
     * Id
     */
    id: string;
    /**
     * Attempt Id
     */
    attempt_id: string;
    /**
     * Question Id
     */
    question_id: string;
    /**
     * Selected Option Id
     */
    selected_option_id: string;
    /**
     * Created At
     */
    created_at: string;
};

/**
 * QuizUpdate
 */
export type QuizUpdate = {
    /**
     * Name
     */
    name?: string | null;
};

/**
 * TokenResponse
 */
export type TokenResponse = {
    /**
     * Access Token
     */
    access_token: string;
    /**
     * Token Type
     */
    token_type?: string;
};

/**
 * UserCreate
 */
export type UserCreate = {
    /**
     * Username
     */
    username: string;
    /**
     * Password
     */
    password: string;
    role?: UserRole | null;
};

/**
 * UserResponse
 */
export type UserResponse = {
    /**
     * Username
     */
    username: string;
    /**
     * Id
     */
    id: string;
    role: UserRole;
    /**
     * Created At
     */
    created_at: string;
};

/**
 * UserRole
 */
export type UserRole = 'admin' | 'user';

/**
 * UserUpdate
 */
export type UserUpdate = {
    /**
     * Username
     */
    username?: string | null;
    /**
     * Password
     */
    password?: string | null;
    role?: UserRole | null;
};

/**
 * ValidationError
 */
export type ValidationError = {
    /**
     * Location
     */
    loc: Array<string | number>;
    /**
     * Message
     */
    msg: string;
    /**
     * Error Type
     */
    type: string;
    /**
     * Input
     */
    input?: unknown;
    /**
     * Context
     */
    ctx?: {
        [key: string]: unknown;
    };
};

export type LoginData = {
    body: LoginRequest;
    path?: never;
    query?: never;
    url: '/auth/login';
};

export type LoginErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type LoginError = LoginErrors[keyof LoginErrors];

export type LoginResponses = {
    /**
     * Successful Response
     */
    200: TokenResponse;
};

export type LoginResponse = LoginResponses[keyof LoginResponses];

export type ListUsersData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/users';
};

export type ListUsersResponses = {
    /**
     * Response List Users
     *
     * Successful Response
     */
    200: Array<UserResponse>;
};

export type ListUsersResponse = ListUsersResponses[keyof ListUsersResponses];

export type CreateUserData = {
    body: UserCreate;
    path?: never;
    query?: never;
    url: '/users';
};

export type CreateUserErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type CreateUserError = CreateUserErrors[keyof CreateUserErrors];

export type CreateUserResponses = {
    /**
     * Successful Response
     */
    201: UserResponse;
};

export type CreateUserResponse = CreateUserResponses[keyof CreateUserResponses];

export type DeleteUserData = {
    body?: never;
    path: {
        /**
         * User Id
         */
        user_id: string;
    };
    query?: never;
    url: '/users/{user_id}';
};

export type DeleteUserErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type DeleteUserError = DeleteUserErrors[keyof DeleteUserErrors];

export type DeleteUserResponses = {
    /**
     * Successful Response
     */
    204: void;
};

export type DeleteUserResponse = DeleteUserResponses[keyof DeleteUserResponses];

export type GetUserData = {
    body?: never;
    path: {
        /**
         * User Id
         */
        user_id: string;
    };
    query?: never;
    url: '/users/{user_id}';
};

export type GetUserErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type GetUserError = GetUserErrors[keyof GetUserErrors];

export type GetUserResponses = {
    /**
     * Successful Response
     */
    200: UserResponse;
};

export type GetUserResponse = GetUserResponses[keyof GetUserResponses];

export type UpdateUserData = {
    body: UserUpdate;
    path: {
        /**
         * User Id
         */
        user_id: string;
    };
    query?: never;
    url: '/users/{user_id}';
};

export type UpdateUserErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type UpdateUserError = UpdateUserErrors[keyof UpdateUserErrors];

export type UpdateUserResponses = {
    /**
     * Successful Response
     */
    200: UserResponse;
};

export type UpdateUserResponse = UpdateUserResponses[keyof UpdateUserResponses];

export type ListQuizzesData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/quizzes';
};

export type ListQuizzesResponses = {
    /**
     * Response List Quizzes
     *
     * Successful Response
     */
    200: Array<QuizResponse>;
};

export type ListQuizzesResponse = ListQuizzesResponses[keyof ListQuizzesResponses];

export type CreateQuizData = {
    body: QuizCreate;
    path?: never;
    query?: never;
    url: '/quizzes';
};

export type CreateQuizErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type CreateQuizError = CreateQuizErrors[keyof CreateQuizErrors];

export type CreateQuizResponses = {
    /**
     * Successful Response
     */
    201: QuizResponse;
};

export type CreateQuizResponse = CreateQuizResponses[keyof CreateQuizResponses];

export type DeleteQuizData = {
    body?: never;
    path: {
        /**
         * Quiz Id
         */
        quiz_id: string;
    };
    query?: never;
    url: '/quizzes/{quiz_id}';
};

export type DeleteQuizErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type DeleteQuizError = DeleteQuizErrors[keyof DeleteQuizErrors];

export type DeleteQuizResponses = {
    /**
     * Successful Response
     */
    204: void;
};

export type DeleteQuizResponse = DeleteQuizResponses[keyof DeleteQuizResponses];

export type GetQuizData = {
    body?: never;
    path: {
        /**
         * Quiz Id
         */
        quiz_id: string;
    };
    query?: never;
    url: '/quizzes/{quiz_id}';
};

export type GetQuizErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type GetQuizError = GetQuizErrors[keyof GetQuizErrors];

export type GetQuizResponses = {
    /**
     * Successful Response
     */
    200: QuizResponse;
};

export type GetQuizResponse = GetQuizResponses[keyof GetQuizResponses];

export type UpdateQuizData = {
    body: QuizUpdate;
    path: {
        /**
         * Quiz Id
         */
        quiz_id: string;
    };
    query?: never;
    url: '/quizzes/{quiz_id}';
};

export type UpdateQuizErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type UpdateQuizError = UpdateQuizErrors[keyof UpdateQuizErrors];

export type UpdateQuizResponses = {
    /**
     * Successful Response
     */
    200: QuizResponse;
};

export type UpdateQuizResponse = UpdateQuizResponses[keyof UpdateQuizResponses];

export type ListQuestionsData = {
    body?: never;
    path: {
        /**
         * Quiz Id
         */
        quiz_id: string;
    };
    query?: never;
    url: '/quizzes/{quiz_id}/questions';
};

export type ListQuestionsErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type ListQuestionsError = ListQuestionsErrors[keyof ListQuestionsErrors];

export type ListQuestionsResponses = {
    /**
     * Response List Questions
     *
     * Successful Response
     */
    200: Array<QuizQuestionResponse>;
};

export type ListQuestionsResponse = ListQuestionsResponses[keyof ListQuestionsResponses];

export type CreateQuestionData = {
    body: QuizQuestionCreate;
    path: {
        /**
         * Quiz Id
         */
        quiz_id: string;
    };
    query?: never;
    url: '/quizzes/{quiz_id}/questions';
};

export type CreateQuestionErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type CreateQuestionError = CreateQuestionErrors[keyof CreateQuestionErrors];

export type CreateQuestionResponses = {
    /**
     * Successful Response
     */
    201: QuizQuestionResponse;
};

export type CreateQuestionResponse = CreateQuestionResponses[keyof CreateQuestionResponses];

export type DeleteQuestionData = {
    body?: never;
    path: {
        /**
         * Question Id
         */
        question_id: string;
    };
    query?: never;
    url: '/quiz-questions/{question_id}';
};

export type DeleteQuestionErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type DeleteQuestionError = DeleteQuestionErrors[keyof DeleteQuestionErrors];

export type DeleteQuestionResponses = {
    /**
     * Successful Response
     */
    204: void;
};

export type DeleteQuestionResponse = DeleteQuestionResponses[keyof DeleteQuestionResponses];

export type GetQuestionData = {
    body?: never;
    path: {
        /**
         * Question Id
         */
        question_id: string;
    };
    query?: never;
    url: '/quiz-questions/{question_id}';
};

export type GetQuestionErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type GetQuestionError = GetQuestionErrors[keyof GetQuestionErrors];

export type GetQuestionResponses = {
    /**
     * Successful Response
     */
    200: QuizQuestionResponse;
};

export type GetQuestionResponse = GetQuestionResponses[keyof GetQuestionResponses];

export type UpdateQuestionData = {
    body: QuizQuestionUpdate;
    path: {
        /**
         * Question Id
         */
        question_id: string;
    };
    query?: never;
    url: '/quiz-questions/{question_id}';
};

export type UpdateQuestionErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type UpdateQuestionError = UpdateQuestionErrors[keyof UpdateQuestionErrors];

export type UpdateQuestionResponses = {
    /**
     * Successful Response
     */
    200: QuizQuestionResponse;
};

export type UpdateQuestionResponse = UpdateQuestionResponses[keyof UpdateQuestionResponses];

export type ListOptionsData = {
    body?: never;
    path: {
        /**
         * Question Id
         */
        question_id: string;
    };
    query?: never;
    url: '/quiz-questions/{question_id}/options';
};

export type ListOptionsErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type ListOptionsError = ListOptionsErrors[keyof ListOptionsErrors];

export type ListOptionsResponses = {
    /**
     * Response List Options
     *
     * Successful Response
     */
    200: Array<QuizQuestionOptionResponse>;
};

export type ListOptionsResponse = ListOptionsResponses[keyof ListOptionsResponses];

export type CreateOptionData = {
    body: QuizQuestionOptionCreate;
    path: {
        /**
         * Question Id
         */
        question_id: string;
    };
    query?: never;
    url: '/quiz-questions/{question_id}/options';
};

export type CreateOptionErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type CreateOptionError = CreateOptionErrors[keyof CreateOptionErrors];

export type CreateOptionResponses = {
    /**
     * Successful Response
     */
    201: QuizQuestionOptionResponse;
};

export type CreateOptionResponse = CreateOptionResponses[keyof CreateOptionResponses];

export type DeleteOptionData = {
    body?: never;
    path: {
        /**
         * Option Id
         */
        option_id: string;
    };
    query?: never;
    url: '/quiz-question-options/{option_id}';
};

export type DeleteOptionErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type DeleteOptionError = DeleteOptionErrors[keyof DeleteOptionErrors];

export type DeleteOptionResponses = {
    /**
     * Successful Response
     */
    204: void;
};

export type DeleteOptionResponse = DeleteOptionResponses[keyof DeleteOptionResponses];

export type GetOptionData = {
    body?: never;
    path: {
        /**
         * Option Id
         */
        option_id: string;
    };
    query?: never;
    url: '/quiz-question-options/{option_id}';
};

export type GetOptionErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type GetOptionError = GetOptionErrors[keyof GetOptionErrors];

export type GetOptionResponses = {
    /**
     * Successful Response
     */
    200: QuizQuestionOptionResponse;
};

export type GetOptionResponse = GetOptionResponses[keyof GetOptionResponses];

export type UpdateOptionData = {
    body: QuizQuestionOptionUpdate;
    path: {
        /**
         * Option Id
         */
        option_id: string;
    };
    query?: never;
    url: '/quiz-question-options/{option_id}';
};

export type UpdateOptionErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type UpdateOptionError = UpdateOptionErrors[keyof UpdateOptionErrors];

export type UpdateOptionResponses = {
    /**
     * Successful Response
     */
    200: QuizQuestionOptionResponse;
};

export type UpdateOptionResponse = UpdateOptionResponses[keyof UpdateOptionResponses];

export type ListAttemptsData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/quiz-attempts';
};

export type ListAttemptsResponses = {
    /**
     * Response List Attempts
     *
     * Successful Response
     */
    200: Array<QuizAttemptResponse>;
};

export type ListAttemptsResponse = ListAttemptsResponses[keyof ListAttemptsResponses];

export type CreateAttemptData = {
    body: QuizAttemptCreate;
    path?: never;
    query?: never;
    url: '/quiz-attempts';
};

export type CreateAttemptErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type CreateAttemptError = CreateAttemptErrors[keyof CreateAttemptErrors];

export type CreateAttemptResponses = {
    /**
     * Successful Response
     */
    201: QuizAttemptResponse;
};

export type CreateAttemptResponse = CreateAttemptResponses[keyof CreateAttemptResponses];

export type DeleteAttemptData = {
    body?: never;
    path: {
        /**
         * Attempt Id
         */
        attempt_id: string;
    };
    query?: never;
    url: '/quiz-attempts/{attempt_id}';
};

export type DeleteAttemptErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type DeleteAttemptError = DeleteAttemptErrors[keyof DeleteAttemptErrors];

export type DeleteAttemptResponses = {
    /**
     * Successful Response
     */
    204: void;
};

export type DeleteAttemptResponse = DeleteAttemptResponses[keyof DeleteAttemptResponses];

export type GetAttemptData = {
    body?: never;
    path: {
        /**
         * Attempt Id
         */
        attempt_id: string;
    };
    query?: never;
    url: '/quiz-attempts/{attempt_id}';
};

export type GetAttemptErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type GetAttemptError = GetAttemptErrors[keyof GetAttemptErrors];

export type GetAttemptResponses = {
    /**
     * Successful Response
     */
    200: QuizAttemptResponse;
};

export type GetAttemptResponse = GetAttemptResponses[keyof GetAttemptResponses];

export type ListResponsesData = {
    body?: never;
    path: {
        /**
         * Attempt Id
         */
        attempt_id: string;
    };
    query?: never;
    url: '/quiz-attempts/{attempt_id}/responses';
};

export type ListResponsesErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type ListResponsesError = ListResponsesErrors[keyof ListResponsesErrors];

export type ListResponsesResponses = {
    /**
     * Response List Responses
     *
     * Successful Response
     */
    200: Array<QuizResponseItemSchema>;
};

export type ListResponsesResponse = ListResponsesResponses[keyof ListResponsesResponses];

export type CreateResponseData = {
    body: QuizResponseCreate;
    path: {
        /**
         * Attempt Id
         */
        attempt_id: string;
    };
    query?: never;
    url: '/quiz-attempts/{attempt_id}/responses';
};

export type CreateResponseErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type CreateResponseError = CreateResponseErrors[keyof CreateResponseErrors];

export type CreateResponseResponses = {
    /**
     * Successful Response
     */
    201: QuizResponseItemSchema;
};

export type CreateResponseResponse = CreateResponseResponses[keyof CreateResponseResponses];

export type DeleteResponseData = {
    body?: never;
    path: {
        /**
         * Response Id
         */
        response_id: string;
    };
    query?: never;
    url: '/quiz-responses/{response_id}';
};

export type DeleteResponseErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type DeleteResponseError = DeleteResponseErrors[keyof DeleteResponseErrors];

export type DeleteResponseResponses = {
    /**
     * Successful Response
     */
    204: void;
};

export type DeleteResponseResponse = DeleteResponseResponses[keyof DeleteResponseResponses];

export type GetResponseData = {
    body?: never;
    path: {
        /**
         * Response Id
         */
        response_id: string;
    };
    query?: never;
    url: '/quiz-responses/{response_id}';
};

export type GetResponseErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type GetResponseError = GetResponseErrors[keyof GetResponseErrors];

export type GetResponseResponses = {
    /**
     * Successful Response
     */
    200: QuizResponseItemSchema;
};

export type GetResponseResponse = GetResponseResponses[keyof GetResponseResponses];

export type ListIalaLightsData = {
    body?: never;
    path?: never;
    query?: {
        /**
         * Category
         *
         * Filter by category (e.g. Kardinaalimerkit, Lateraalimerkit)
         */
        category?: string | null;
        /**
         * Search
         *
         * Search by name, rhythm, or description
         */
        search?: string | null;
    };
    url: '/iala-lights';
};

export type ListIalaLightsErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type ListIalaLightsError = ListIalaLightsErrors[keyof ListIalaLightsErrors];

export type ListIalaLightsResponses = {
    /**
     * Response List Iala Lights
     *
     * Successful Response
     */
    200: Array<IalaLightResponse>;
};

export type ListIalaLightsResponse = ListIalaLightsResponses[keyof ListIalaLightsResponses];

export type CreateIalaLightData = {
    body: IalaLightCreate;
    path?: never;
    query?: never;
    url: '/iala-lights';
};

export type CreateIalaLightErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type CreateIalaLightError = CreateIalaLightErrors[keyof CreateIalaLightErrors];

export type CreateIalaLightResponses = {
    /**
     * Successful Response
     */
    201: IalaLightResponse;
};

export type CreateIalaLightResponse = CreateIalaLightResponses[keyof CreateIalaLightResponses];

export type DeleteIalaLightData = {
    body?: never;
    path: {
        /**
         * Light Id
         */
        light_id: string;
    };
    query?: never;
    url: '/iala-lights/{light_id}';
};

export type DeleteIalaLightErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type DeleteIalaLightError = DeleteIalaLightErrors[keyof DeleteIalaLightErrors];

export type DeleteIalaLightResponses = {
    /**
     * Successful Response
     */
    204: void;
};

export type DeleteIalaLightResponse = DeleteIalaLightResponses[keyof DeleteIalaLightResponses];

export type GetIalaLightData = {
    body?: never;
    path: {
        /**
         * Light Id
         */
        light_id: string;
    };
    query?: never;
    url: '/iala-lights/{light_id}';
};

export type GetIalaLightErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type GetIalaLightError = GetIalaLightErrors[keyof GetIalaLightErrors];

export type GetIalaLightResponses = {
    /**
     * Successful Response
     */
    200: IalaLightResponse;
};

export type GetIalaLightResponse = GetIalaLightResponses[keyof GetIalaLightResponses];

export type UpdateIalaLightData = {
    body: IalaLightCreate;
    path: {
        /**
         * Light Id
         */
        light_id: string;
    };
    query?: never;
    url: '/iala-lights/{light_id}';
};

export type UpdateIalaLightErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type UpdateIalaLightError = UpdateIalaLightErrors[keyof UpdateIalaLightErrors];

export type UpdateIalaLightResponses = {
    /**
     * Successful Response
     */
    200: IalaLightResponse;
};

export type UpdateIalaLightResponse = UpdateIalaLightResponses[keyof UpdateIalaLightResponses];
