/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as COLREGQuizRouteImport } from './routes/COLREG-quiz'
import { Route as IALARouteImport } from './routes/IALA'
import { Route as IALAQuizRouteImport } from './routes/IALA-quiz'
import { Route as ColregsRouteImport } from './routes/colregs'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const COLREGQuizRoute = COLREGQuizRouteImport.update({
  id: '/COLREG-quiz',
  path: '/COLREG-quiz',
  getParentRoute: () => rootRouteImport,
} as any)
const IALARoute = IALARouteImport.update({
  id: '/IALA',
  path: '/IALA',
  getParentRoute: () => rootRouteImport,
} as any)
const IALAQuizRoute = IALAQuizRouteImport.update({
  id: '/IALA-quiz',
  path: '/IALA-quiz',
  getParentRoute: () => rootRouteImport,
} as any)
const ColregsRoute = ColregsRouteImport.update({
  id: '/colregs',
  path: '/colregs',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/COLREG-quiz': typeof COLREGQuizRoute
  '/IALA': typeof IALARoute
  '/IALA-quiz': typeof IALAQuizRoute
  '/colregs': typeof ColregsRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/COLREG-quiz': typeof COLREGQuizRoute
  '/IALA': typeof IALARoute
  '/IALA-quiz': typeof IALAQuizRoute
  '/colregs': typeof ColregsRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/COLREG-quiz': typeof COLREGQuizRoute
  '/IALA': typeof IALARoute
  '/IALA-quiz': typeof IALAQuizRoute
  '/colregs': typeof ColregsRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/COLREG-quiz' | '/IALA' | '/IALA-quiz' | '/colregs'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/COLREG-quiz' | '/IALA' | '/IALA-quiz' | '/colregs'
  id: '__root__' | '/' | '/COLREG-quiz' | '/IALA' | '/IALA-quiz' | '/colregs'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  COLREGQuizRoute: typeof COLREGQuizRoute
  IALARoute: typeof IALARoute
  IALAQuizRoute: typeof IALAQuizRoute
  ColregsRoute: typeof ColregsRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/COLREG-quiz': {
      id: '/COLREG-quiz'
      path: '/COLREG-quiz'
      fullPath: '/COLREG-quiz'
      preLoaderRoute: typeof COLREGQuizRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/IALA': {
      id: '/IALA'
      path: '/IALA'
      fullPath: '/IALA'
      preLoaderRoute: typeof IALARouteImport
      parentRoute: typeof rootRouteImport
    }
    '/IALA-quiz': {
      id: '/IALA-quiz'
      path: '/IALA-quiz'
      fullPath: '/IALA-quiz'
      preLoaderRoute: typeof IALAQuizRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/colregs': {
      id: '/colregs'
      path: '/colregs'
      fullPath: '/colregs'
      preLoaderRoute: typeof ColregsRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  COLREGQuizRoute: COLREGQuizRoute,
  IALARoute: IALARoute,
  IALAQuizRoute: IALAQuizRoute,
  ColregsRoute: ColregsRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
